import Home from "./home";;
import Login from "./login";
import Register from "./register";
import Welcome from "./Welcome";
import ForgotPassword from "./forgotPassword";
import Settings from './settings';
import ChangePassword from "./changePassword";
import Contact from "./contact";
import { SubCategory } from "./home/components";
import Payment from "./payment";
export { Home, Login, Register, Welcome, ForgotPassword, Settings, ChangePassword, Contact, SubCategory, Payment };