export const actionType = {

    LOADING: "LOADING",

    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAIL: "SIGNUP_FAIL",
    GET_LOGGED_USER_SUCCESS: "GET_LOGGED_USER_SUCCESS",
    GET_LOGGED_USER_FAIL: "GET_LOGGED_USER_FAIL",
    USER_SIGNOUT: "USER_SIGNOUT",
    GET_CARS_SUCCESS: "GET_CARS_SUCCESS",
    GET_CARS_FAIL: "GET_CARS_FAIL",
    GET_CARS_TYPE_SUCCESS: "GET_CARS_TYPE_SUCCESS",
    GET_CARS_TYPE_FAIL: "GET_CARS_TYPE_FAIL"

}